# https://gist.github.com/inao/f55e8232e150aee918b9
# from WEB+DB PRESS
# 対応は不完全(途中で飽きた) 一部手心を加えている
version: 1
rules:
  - expected: Cookie
    pattern:  クッキー
  - expected: Cookie
  - expected: Web
  - expected: Web
    pattern:
      - ウェブ
      - ウェッブ
  - expected: アイデア
    pattern:
      - アィディア
      - アイディア
      - アィデア
  - expected: アスタリクス
    pattern:  アステリスク
  - expected: アーキテクチャ
    pattern:
      - アーキテクチャー
      - アーキテクチャ
  - expected: アクティビティ
    pattern:  アクティビティー
  - expected: アダプタ
    pattern:  アダプター
  - expected: アノテーション
    pattern: アノーテーション
  - expected: アダプタ
    pattern: アダプター
  - expected: アプレット
    pattern: Applet
  - expected: アプリケーション
    pattern: /アプリ(?!ケ)/
    specs:
      - from: アプリケーション
        to:   アプリケーション
      - from: アプリ
        to:   アプリケーション
  - expected: アニメータ
    pattern:  アニメーター
  - expected: アンダースコア
    pattern:  アンダーバー
  - expected: インストーラ
    pattern:  インストーラー
  - expected: インスパイア
    pattern:  インスパイヤ
  - expected: インタフェース
    pattern:
      - インタフェイス
      - インターフェイス
      - インターフェース
      - インターフェイス
  - expected: インタプリタ
    pattern:
      - インタープリタ
      - インタプリター
      - インタープリター
  - expected: インデックス
    pattern:  インデクス
  - expected: インテント
    pattern:  Intent
  - expected: ウィジェット
    pattern:
      - Widget
      - widget
  - expected: ウィルス
    pattern:  ウイルス
  - expected: ウィンドウ
    pattern:  ウインドウ
  - expected: ウェア
    pattern:  ウエア
    spec:
      - from: ハードウエア
        to:   ハードウェア
  - expected: エディタ
    pattern:  エディター
  - expected: エミッタ
    pattern:  エミッター
  - expected: エンコーダ
    pattern:  エンコーダー
  - expected: デコーダ
    pattern:  デコーダー
  - expected: エミュレータ
    pattern:  エミュレーター
  - expected: エンティティ
    pattern:
      - Entity
      - entity
      - エンティティー
  - expected: エントリ
    pattern:  エントリー
  - expected: オプション
    pattern:  オブション
  - expected: カウンタ
    pattern:  カウンター
  - expected: ガベージ
    pattern:
      - ガベージ・
      - ガーベジ・
      - ガーベジ
      - ガーベージ・
      - ガーベージ
      - ガーベッジ・
      - ガーベッジ
  - expected: カテゴリ
    pattern:  カテゴリー
  - expected: キャラクタ
    pattern:  キャラクター
  - expected: キャッシュ
    pattern:
      - /cache(?![^a-zA-Z\-])/
      - /Cache(?![^a-zA-Z\-])/
  - expected: クエリ文字列
    pattern:
      - QueryString
      - Query String
      - クエリストリング
      - クエリーストリング
  - expected: クエリ
    pattern:  クエリー
  - expected: クライアント／サーバ
    pattern:
      - クライアント/サーバー
      - クライアント/サーバ
      - クライアント・サーバー
      - クライアント・サーバ
      - クライアントサーバー
      - クライアントサーバ
    specs:
      - from: クライアント/サーバー
        to:   クライアント／サーバ
  - expected: クラスタ
    pattern:  クラスター
  - expected: グラウンド
    pattern:  グランド
  - expected: グリッド
    pattern:  Grid
  - expected: クロージャ
    pattern:  クロージャー
  - expected: ゲッタ
    pattern:  ゲッター
  - expected: コピー&ペースト
    pattern:
      - コピー＆ペースト
      - コピペ
      - コピーアンドペースト
  - expected: コミッタ
    pattern:  コミッター
  - expected: コミュニ
    pattern:  コミニュ
  - expected: コンストラクタ
    pattern:  コンストラクター
  - expected: コンテキスト
    pattern:  コンテクスト
  - expected: コンテントプロバイダ
    pattern:  Content provider
  - expected: コンテナ
    pattern:  コンテナー
  - expected: コンピュータ
    pattern:  コンピューター
  - expected: コントローラ
    pattern:  コントローラー
  - expected: サーバ
    pattern:  サーバー
  - expected: サーブレット
    pattern:
      - Servlet
      - SERVLET
  - expected: サーブレット/JSP
    pattern:
      - サーブレット／JSP
      - サーブレット＆JSP
      - サーブレット&JSP
  - expected: ジェネレータ
    pattern:  ジェネレーター
  - expected: ジョブズ
    pattern:  ジョブス
  - expected: ジオタグ
    pattern:
      - Geotag
      - geotag
  - expected: シミュレー
    pattern:  シュミレー
  - expected: スカラ
    pattern:  スカラー
  - expected: スタンドアローン
    pattern:  スタンドアロン
  - expected: ストアド
    pattern:  ストアード
  - expected: ストレージ
    pattern:
      - ストレッジ
      - ストレジ
  - expected: セキュリティ
    pattern:  セキュリティー
  - expected: セッション
    pattern:
      - session
      - Session
  - expected: セッタ
    pattern:  セッター
  - expected: セレクタ
    pattern:  セレクター
  - expected: ソフトウェア
    pattern: /(日経)?ソフトウエア/
    regexpMustEmpty: $1
    specs:
      - from: 広義のソフトウエア
        to:   広義のソフトウェア
      - from: 日経ソフトウエア
        to:   日経ソフトウエア
  - expected: ダイアグラム
    pattern:  ダイヤグラム
  - expected: タイムスタンプ
    pattern:
      - timestamp
      - Timestamp
  - expected: ツイート
    pattern:
      - tweet
      - Tweet
      - ツィート
  - expected: ツリーオブジェクト
    pattern:  ツリー・オブジェクト
  - expected: ツリーエントリ
    pattern:  ツリー・エントリ
  - expected: テーブル
    pattern:
      - table
      - Table
  - expected: ディレクター
    pattern:  /ディレクタ(?!ー)/
    specs:
      - from: ディレクター
        to:   ディレクター
  - expected: データサービス
    pattern:  Data Services
  - expected: データ同期
    pattern:  Data Sync
  - expected: チェイン
    pattern:  チェーン
  - expected: ディスク
    pattern:  Disk
  - expected: ディスパッチャ
    pattern:  ディスパッチャー
  - expected: ディスプレイ
    pattern:  ディスプレー
  - expected: ディレクトリ
    pattern:  ディレクトリー
  - expected: テクノロジ
    pattern:  テクノロジー
  - expected: デザイナ
    pattern:  デザイナー
  - expected: デバッグ
    pattern:  デバック
  - expected: デフォルト
    pattern:
      - 既定
      - ディフォルト
      - デフォールト
  - expected: デプロイ
    pattern:  デプロイメント
  - expected: デベロッパ
    pattern:
      - ディベロッパー
      - ディベロッパ
      - デベロッパー
      - ディヴェロッパ
  - expected: デリバリ
    pattern:  デリバリー
  - expected: ドキュメント
    pattern:  ドキュメンテーション
  - expected: ドライバ
    pattern:  ドライバー
  - expected: ドラッグ&ドロップ
    pattern:
      - ドラッグ・アンド・ドロップ
      - ドラッグアンドドロップ
      - ドラッグ＆ドロップ
  - expected: ハイパーリンク
    pattern:  ハイパー・リンク
  - expected: パーサ
    pattern:
      - パーサー
      - パーザー
      - パーザ
  - expected: パーマリンク
    pattern:
      - Permalink
      - permalink
      - permanent link
      - パーマネントリンク
  - expected: バッファ
    pattern:  バッファー
  - expected: パス
    pattern:
      - path
      - Path
  - expected: パターン
    pattern:  パタン
  - expected: ハッシュ
    pattern:
      - hash
      - Hash
  - expected: バラ
    pattern:  薔薇
  - expected: バラエティ
    pattern:  バラエティー
  - expected: パラメータ
    pattern:  パラメーター
  - expected: バランサ
    pattern:  バランサー
  - expected: ハンドラ
    pattern:  ハンドラー
  - expected: ヒット率
    pattern:  Hit率
  - expected: ファイラ
    pattern: ファイラー
  - expected: ファクトリ
    pattern:  ファクトリー
  - expected: フィーチャーフォン
    pattern:  フィーチャフォン
  - expected: ブラウザ
    pattern:
      - /Webブラウザー?/
      - /WEBブラウザー?/
      - ブラウザ
  - expected: プライマリ
    pattern:  プライマリー
  - expected: プラットフォーム
    pattern:  プラットホーム
  - expected: プレフィックス
    pattern:
      - プレフィクス
      - プリフィックス
  - expected: プレイヤー
    pattern:  プレーヤ
  - expected: ブレーク
    pattern:  ブレイク
  - expected: プレーン
    pattern:  プレイン(?!グ)
    specs:
      - from: プレイング
        to:   プレイング
  - expected: プロパティ
    pattern:  プロパティー
  - expected: ヘビー
    pattern:  ヘヴィ
  - expected: レビュア
    pattern:
      - レビュアー
      - レビュワー
      - レビュワ
      - レビューアー
      - レビューア
      - レビューワー
      - レビューワ
  - expected: ビューア
    pattern:
      - ビューアー
      - ビューワー
      - ビューワ
  - expected: ファイアウォール
    pattern:
      - ファイアーウォール
      - ファイヤーウォール
      - ファイヤウォール
      - ファイヤーウオール
  - expected: フィルタ
    pattern:  フィルター
  - expected: フィクスチャ
    pattern:  フィクスチャー
  - expected: フェイルオーバー
    pattern:
      - フェイルオーバ
      - フェールオーバー
      - フェールオーバ
  - expected: フェーズ
    pattern:  フェイズ
  - expected: フッタ
    pattern:
      - フッター
      - フッダ
  - expected: プロキシ
    pattern:
      - プロクシ
      - プロクシー
      - プロキシー
      - Proxy
      - proxy
  - expected: ブログ
    pattern: /(?![^/])(?:blog|Blog)(?![^/])/
    specs:
      - from: http://blog.example.com/
        to:   http://blog.example.com/
      - from: http://example.com/foo-blog/
        to:   http://example.com/foo-blog/
  - expected: プログラマ
    pattern:  プログラマー
  - expected: プロシージャ
    pattern:  プロシージャー
  - expected: プロバイダ
    pattern:  プロバイダー
  - expected: ベンダー
    pattern:  ベンダ
  - expected: ヘッダ
    pattern:
      - ヘッダー
      - ヘッター
      - ヘッタ
  - expected: ベクタ
    pattern:  ベクター
  - expected: ページャ
    pattern:  ページャー
  - expected: ポインタ
    pattern:  ポインター
  - expected: ポリモフィズム
    pattern:
      - ポリモルフィズム
      - ポリモーフィズム
      - ポルモルフィズム
  - expected: マトリックス
    pattern:  マトリクス
  - expected: マッパ
    pattern:
      - マッピングツール
      - マッパー
  - expected: マネジメント
    pattern:  マネージメント
  - expected: メーカー
    pattern:  メーカ
  - expected: メーリングリスト
    pattern:  /\bML\b(?!系)/
    specs:
      - from: SML#
        to:   SML#
      - from: ML系言語
        to:   ML系言語
      - from: MLなど
        to:   メーリングリストなど
  - expected: メタファ
    pattern:  メタファー
  - expected: メモリ
    pattern:  メモリー
  - expected: メンテナンス
    pattern:  メインテナンス
  - expected: メンテナ
    pattern:  メンテナー
  - expected: メンバー
    # 人間の意味では「メンバー」、変数などは「メンバ」
    pattern:  /メンバ(?!ー)/
  - expected: リーダー
    # 人間の意味では「リーダー」、readerの意味では「リーダ」
    pattern:  /リーダ(?!ー)/
  - expected: レジューム
    pattern:  リジューム
  - expected: モジュール
    pattern:
      - module
      - Module
  - expected: ユーザ
    pattern:  ユーザー
  - expected: ユーティリティ
    pattern:  ユーティリティー
  - expected: ユニットテスト
    pattern:
      - Unitテスト
      # 単体テストはケースバイケース
      - 単体テスト
  - expected: ライブラリ
    pattern:  ライブラリー
  - expected: ラッパ
    pattern:  ラッパー
  - expected: リグレッション
    pattern:
      - デグレード
      # デグレは英語圏では使わない by Jenkins川口さん
      - デグレ
  - expected: リスナ
    pattern:  リスナー
  - expected: リファラ
    pattern:  リファラー
  - expected: リポジトリ
    pattern:
      - リポジトリー
      - レポジトリ
      - レポジトリー
  - expected: ルータ
    pattern:  ルーター
  - expected: レイヤ
    pattern:  /(プ)?レイヤー/
    regexpMustEmpty: $1
    specs:
      - from: レイヤー
        to:   レイヤ
      - from: プレイヤー
        to:   プレイヤー
  - expected: レジストリ
    pattern:  レジストリー
  - expected: レイテンシ
    pattern:  レイテンシー
  - expected: ローダ
    pattern:  ローダー
  - expected: ワーカ
    pattern:
      - ワーカー
      - worker
